### ISSUE TITLE
Document features in README

### ISSUE THREAD

**Issue by mojavelinux** [middleman/middleman-asciidoc#18]
Add documentation to README that explains the features provided by this extension and how to use them.

Features to cover include:

* Activating the extension and configuration Asciidoctor using extension options
  - alternate: configuring Asciidoctor using site-wide config
* Defining page-layout (and page-layout-engine) for a page. See https://github.com/middleman/middleman-asciidoc/issues/13#issuecomment-170411888
* Defining page metadata using the AsciiDoc header. See https://github.com/middleman/middleman-asciidoc/issues/16#issue-125813215
* Defining base_dir
* Location of imagesdir (automatically assigned from Middleman config)
* How to write blog posts in AsciiDoc when using middleman-blog (probably better handled as a separate issue)

**Comment by drallgood** [comment]
I will try to take care of that over the weekend

**Comment by mojavelinux** [comment]
Excellent!

If you need help with the outline/topics, feel free to post some sketches in comments and I'll be sure to provide whatever input I can.
