### ISSUE TITLE
Rewrite file extension .adoc in relative links to .html

### ISSUE THREAD

**Issue by jirutka** [middleman/middleman-asciidoc#37]
`link:doc/linux.adoc[Linux]` is converted to `<a href="doc/linux.adoc">Linux</a>`, but the actual target file is `doc/linux.html`, not `doc/linux.adoc`.

**Comment by jirutka** [comment]
The solution is to use [Inter-document Cross References](http://asciidoctor.org/docs/user-manual/#inter-document-cross-references) instead of plain `link` macro. For example `<<doc/linux, Linux>>` is converted to `<a href="doc/linux.html">Linux</a>` when HTML converter is used or `<a href="doc/linux.adoc">Linux</a>` when viewing on GitHub.

Cross references are the correct solution for this, but maybe it’d be still helpful to convert relative links with `.adoc` extension passed to `link` macro.

**Comment by mojavelinux** [comment]
You got it. Inter-document cross references are the solution. I don't think we should mess with the target of link since that is intended to be an explicit target. However, you can write the link macro in such a way as to make the extension dynamic.

```
link:doc/linux{outfilesuffix}[Linux]
```

This technique is often used on GitHub. See http://asciidoctor.org/docs/user-manual/#navigating-between-source-files

**Comment by novabyte** [comment]
@mojavelinux Is there a way to make the `link` macro work like Middleman's `link_to` helper? I use the `directory_indexes` extension and am not sure how I should format links in Asciidoc to convert them to pretty URLs as generated by Middleman?

**Comment by novabyte** [comment]
I wonder would it be possible to monkeypatch the `link` macro in `asciidoctor` so I could push it through the `link_to` helper and it'd obey changes like those activated by the `directory_indexes` extension?

**Comment by novabyte** [comment]
I've made some more progress on how to monkeypatch the necessary code to use Middleman's `link_to` helper.  I'm not a Ruby programmer; the code below doesn't work but I'm close I think. I'm not really sure how to call `link_to` from Middleman/Padrino in the function?

```ruby
require 'asciidoctor/converter/html5'
require 'padrino-helpers/asset_tag_helpers'

Asciidoctor::Converter::Html5Converter.class_eval do
  def inline_anchor node
    target = Padrino::Helpers::AssetTagHelpers.link_to(node.target)
    case node.type
    when :xref
      refid = node.attributes['refid'] || target
      # NOTE we lookup text in converter because DocBook doesn't need this logic
      text = node.text || (node.document.references[:ids][refid] || %([#{refid}]))
      # FIXME shouldn't target be refid? logic seems confused here
      %(<a href="#{target}">#{text}</a>)
    when :ref
      %(<a id="#{target}"></a>)
    when :link
      attrs = []
      attrs << %( id="#{node.id}") if node.id
      if (role = node.role)
        attrs << %( class="#{role}")
      end
      attrs << %( title="#{node.attr 'title'}") if node.attr? 'title', nil, false
      attrs << %( target="#{node.attr 'window'}") if node.attr? 'window', nil, false
      %(<a href="#{target}"#{attrs.join}>#{node.text}</a>)
    when :bibref
      %(<a id="#{target}"></a>[#{target}])
    else
      warn %(asciidoctor: WARNING: unknown anchor type: #{node.type.inspect})
    end
  end
end
```

**Comment by mojavelinux** [comment]
I've documented how this works in the README. See https://github.com/middleman/middleman-asciidoc#linking-between-pages.

We might still want to have a custom macro or something that goes a bit deeper. But this at least covers the basics.
