### ISSUE TITLE
Does not generate usable files

### ISSUE THREAD

**Issue by drallgood** [middleman/middleman-asciidoc#7]
Hi.
Just started using middleman and this plugin and it doesn't seem to be working anymore.
When you build the site (middleman site) the doc files are converted to html, but lack any sort of file extension. That results in the files not being served as HTML files, but plain-text files instead.

**Comment by dg-ratiodata** [comment]
@tdreyno I think this plugin needs an update or needs to be removed from `middleman` organization.

**Comment by dg-ratiodata** [comment]
@mojavelinux Thoughts?

**Comment by tdreyno** [comment]
yeah, pulled this out of core into an extension for v4... but never actually kept it up to date.

**Comment by mojavelinux** [comment]
We (the Asciidoctor project) have full intention of supporting this plugin (esp since I'll personally be using it for my site), but at the time we were waiting the changes to play out in v4 and for the final release. Since that's now happened, I'm happy to get back to bringing this in line with the v4 APIs and getting it working properly again.

I am definitely interested in help maintaining it. @drallgood if you are interested, let me know and I'll add you to the committers list (which in git terms means write access to this repo).

**Comment by mojavelinux** [comment]
Regarding $subject.

This happens because your file is named with a `.adoc` extension instead of a `.html.adoc` extension. It seems to be a new requirement in Middleman v4 that the output file extension is derived by removing the last part. I don't know how to configure it otherwise. @tdreyno can you advise? Is there a way to have a fallback file extension when it isn't included in the source file name?

**Comment by mojavelinux** [comment]
You can see that even the middleman guides site follows this file naming convention for Markdown files: https://github.com/middleman/middleman-guides/tree/master/source/basics

**Comment by mojavelinux** [comment]
All the tests are now passing on Travis CI. However, the tests do not run on JRuby 9k. See https://travis-ci.org/middleman/middleman-asciidoc/jobs/100728152

**Comment by drallgood** [comment]
@mojavelinux I'd be happy to help.
I'm pretty new to middleman, but I've worked on octopress/jekyll previously so this shouldn't be too difficult to figure out ;)

**Comment by mojavelinux** [comment]
Excellent!

**Comment by mojavelinux** [comment]
Oops, I was just trying to setup a team and I managed to remove myself as an admin (how is that even possible?). @bhollis or @tdreyno, could you give the middleman-asciidoc team Admin rights again or make me the owner of the repository. I can't even see the settings page anymore.

**Comment by tdreyno** [comment]
GH changed their repo permission stuff recently. Just added you as a repo admin.

**Comment by mojavelinux** [comment]
Thanks @tdreyno!

**Comment by mojavelinux** [comment]
One more thing. Can you add @drallgood to the team middleman-asciidoc-committers? Apparently I can't invite people who aren't already on a team in the middleman org.

**Comment by tdreyno** [comment]
Done

**Comment by mojavelinux** [comment]
Thanks @tdreyno!

Now, any insight on why the double extension is required for markup files? Is there a way to tell Middleman to add an extension if the output file ends up without one? (input.adoc => output.html). I looked at the code but I just couldn't figure out where it was writing the output file.

**Comment by mojavelinux** [comment]
I'm assuming that this is the same question for Markdown (input.md => output.html).

**Comment by tdreyno** [comment]
@mojavelinux That bit of magic was removed in favor of being explicit.

**Comment by mojavelinux** [comment]
Thanks for clarifying @tdreyno. The problem I see is that's going to lead to a ton of support requests because people are going to want to put their .adoc files in the site and have them be rendered, possibly files they are including from another project. AsciiDoc files, esp are not tied to HTML, so it makes even less sense that we require information about the output format to be included in the input file.

Is there any hook at all I can tap into to change this behavior at least for .adoc files?

**Comment by drallgood** [comment]
@mojavelinux I think I might have found a way. Still trying to verify the impact, though.

I basically manipulated the destination_path of the resource.

**Comment by tdreyno** [comment]
@drallgood that's what I would do. The feature was removed because it touches so much code (layouts, partials, templates, mime types). If you're safe to hardcode something for your specific format that doesn't need all that, then it should be safe.

**Comment by mojavelinux** [comment]
:+1:

**Comment by drallgood** [comment]
Great.

@mojavelinux The one thing I had to fix were the cucumber tests. For some odd reason they were already using the correct file extension.

**Comment by mojavelinux** [comment]
That's because I think I had switched all the example files over to using .html.adoc. That was giving us a false positive (in the sense that they are faithfully using the required mapping). (see https://github.com/middleman/middleman-asciidoc/tree/master/fixtures/asciidoc-app/source)

**Comment by drallgood** [comment]
Damn. How did I miss that... :wink:

**Comment by drallgood** [comment]
fixed :)

**Comment by mojavelinux** [comment]
Nice work. We ended up trying to add the same test for the double file extension, so I'm glad we both caught that. I changed it to check for `ends_with? '.html'` instead of include? so it is more accurate.

**Comment by mojavelinux** [comment]
I also added a note why we use '<<' (String mutation) and not a direct assignment. It seems that by assigning the value, it breaks layouts, presumably because of this line: https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/sitemap/resource.rb#L136

**Comment by mojavelinux** [comment]
As we move forward on fixing other issues, I have a few requests for our workflow:

* always commit to master via a pull request, esp when it resolves an issue; you can merge your own pull request, but wait a few hours (24 is ideal) at least for comment
* name the branch after the issue (e.g., issue-N where N is the issue number)
* begin the commit message with `resolves #N` where N is the issue number (if the commit maps to an issue, as it should)

That way, we provide an opportunity for code review and encourage participation. Sound good?

**Comment by mojavelinux** [comment]
I suppose we should add that info to the README. I'll wait for your :+1:  first.

**Comment by drallgood** [comment]
Sounds good to me :+1:

**Comment by mojavelinux** [comment]
Cool!

I updated the issue title so it's more clear for people who come looking for it.

**Comment by mojavelinux** [comment]
I'm going to borrow the contribution-code guide from Asciidoctor.js because it's pretty well done.

**Comment by drallgood** [comment]
Yeah. That one is pretty good!

**Comment by mojavelinux** [comment]
Proposal sent! I ended up writing something original. I think it's gets to the heart of the matter in few number of words.

**Comment by mojavelinux** [comment]
See https://github.com/mojavelinux/middleman-asciidoc/blob/issue-11/CONTRIBUTING.adoc
