### ISSUE TITLE
Change file extension 

### ISSUE THREAD

**Issue by supsup** [middleman/middleman-asciidoc#87]
Is there a property to change the output from .html, to .xyz?
for different lang backed systems like java etc? ( .jsp / .gsp )

**Comment by mojavelinux** [comment]
Have you tried to set the outfilesuffix in the global AsciiDoc attribute?

https://github.com/middleman/middleman-asciidoc#activation-and-configuration

**Comment by supsup** [comment]
Think so:
```
# Configure the AsciiDoc renderer
activate :asciidoc, 
    attributes: { 
        'header_footer' => false, 
        'toc' => false,
        'outfilesuffix' => ".gsp", 
    },
    layout: "layout.erb"
```

**Comment by supsup** [comment]
relfilesuffix does not seem to work either.

**Comment by supsup** [comment]
Oddly in MM3, if you set
`:outfilesuffix: .gsp` in an .adoc file it does convert other .adoc links in that file to have .gsp extensions.

ultimately trying to get MM4 to work tho, was just comparing.

**Comment by mojavelinux** [comment]
relfilesuffix is coming in 1.5.7. I should have said "you will have to set"

**Comment by mojavelinux** [comment]
I just submitted a PR with a slight change and more tests.

Here are the new rules:

* If the file has a double file extension (e.g., .gsp.adoc), use the first file extension for the output file (e.g., .gsp) (in this case, you don't have to set the outfilesuffix attribute, which will be ignored anyway)
* If the file has a single file extension (e.g., .adoc), use the file extension specified by the outfilesuffix attribute (which defaults to .html)

**Comment by mojavelinux** [comment]
Let's handled the file extension for interdoc xrefs in a separate issue.

**Comment by mojavelinux** [comment]
There's now a test in place to prove that outfilesuffix can be set (either the global AsciiDoc attributes or per page).
