### ISSUE TITLE
Problems rendering a custom toc / block_outline.html.slim

### ISSUE THREAD

**Issue by marcobehler** [middleman/middleman-asciidoc#88]
Hi @mojavelinux ,
I've got a Middleman 4.2.1 project, with a 
`\source\_asciidoc_templates\block_outline.html.slim` file ([Link](https://github.com/asciidoctor/asciidoctor-backends/blob/master/slim/html5/block_outline.html.slim)), which I copied from the asciidoctor-backends project.

Furthermore I have a layout file, which calls the following method:

```
<div class="sidebar">
  <% if (doc = current_page.data.document) %>
    <%= doc.converter.convert doc, 'outline', toclevels: 3 %>
   <% end %>
</div>
```

Now i know that the block_outline.html.slim file is getting applied correctly (i.e. I also made the necessary changes to config.rb), because I get the following error message when trying to render my pages:

> undefined method `section_level' for #<Asciidoctor::Document:0x007fffe50b9ea0> Did you mean? sections
> 
> Ruby | /mnt/c/dev/blah/source/_asciidoc_templates/block_outline.html.slim: in block in singleton class, line 3

What am I missing? Why does it not find the helper appropriate helper methods?

Thank you!
Marco

**Comment by mojavelinux** [comment]
Did you copy the helpers.rb to \source\_asciidoc_templates\ too?

**Comment by marcobehler** [comment]
Of course.....not :D

For anyone else interested in this: Copying the file over is however only half the story. You need to add the following to your Gemfile

`gem 'opal', '~> 0.10.5'`

**Note** You need to specify the version, as with newer versions of the opal gem it won't work.

Thanks @mojavelinux !

**Comment by mojavelinux** [comment]
You can avoid the problem with Opal being used by setting the template_engine option. Otherwise, tilt goes a little crazy and tries to use Opal to compile the helper file.

**Comment by mojavelinux** [comment]
Actually, it turns out the problem is putting the templates under the source folder. We don't want Middleman looking at those files, so it's best to move them outside the source directory. Then only Asciidoctor processes them, and it doesn't do stupid things like try to load Opal. I updated the README.

**Comment by mojavelinux** [comment]
See the README. Move the whole templates folder. It was wrong of me to
suggest that it goes inside source since Middleman monitors that folder.

**Comment by marcobehler** [comment]
Thank you!
