### ISSUE TITLE
Unable to soft unset built-in attributes in Asciidoctor

### ISSUE THREAD

**Issue by FiveYellowMice** [middleman/middleman-asciidoc#93]
Reading from #72, I suppose that providing `'!name' => '@'` in attributes should soft unset a built-in attribute in Asciidoctor, but in fact the result is the same as a hard unset. The `'-name' => ''` syntax only stops this extension from passing an attribute to Asciidoctor. Using `'name' => false` does a hard reset, too.

I guess the culprit is `Middleman::AsciiDoc::AsciiDocExtension#merge_attributes`, which seems to set the value of the hash to nil as long as the key starts or ends with a `!`. It also converts all falses to nils (Is there a reason to do this?).

**Comment by mojavelinux** [comment]
That feature was added to Asciidoctor after this extension was developed. Therefore, support for it must be added.

I'm not currently working on this project. However, I'd be willing to review and help merge a proposed change.

**Comment by FiveYellowMice** [comment]
Sure, I'll work on it.
