### ISSUE TITLE
Method to promote custom AsciiDoc attributes to page data

### ISSUE THREAD

**Issue by FiveYellowMice** [middleman/middleman-asciidoc#94]
Right now, attributes other than doctitle, author, authors, email, revdate, keywords, description can only become page data if they are prepend with `page-`. But it would be nice to have an extension option of additional attributes to promote to page data without the `page-` prefix. For example, writing `page-tags` attributes in a blog article feels weird because tags feel like properties of the article itself rather than properties of the generated webpage (unlike `page-layout`).

**Comment by mojavelinux** [comment]
Yes, I like the idea of having the ability to specify additional attributes to auto promote.

**Comment by FiveYellowMice** [comment]
Hi, I have created a PR on #98, do you mind reviewing it?
